version: "3"
services:
  postgres-local:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "2fe62e24-fb14-41d4-be56-afbce0cd3f04"
      POSTGRES_USER: "integration_testing"
    volumes:
      - es-postgres-local-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready"
      interval: 5s
    ports:
      - "5432:5432"
volumes:
  es-postgres-local-db-volume:
