version: '3.3'
services:
    postgres:
        container_name: pg-docker
        environment:
            - POSTGRES_USER=integration_testing
            - POSTGRES_PASSWORD=2fe62e24-fb14-41d4-be56-afbce0cd3f04
        ports:
            - '5432:5432'
        volumes:
            - '$HOME/docker/volumes/postgres:/var/lib/postgresql/data'
        image: postgres:11-alpine
